[package]
name = "teleporter-factory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mustache = "0.9.0"
serde = { version = "1.0.193", features = ["derive"] }
tar = "0.4.40"
toml = "0.8.8"
