display_name = "SomeOtherVPN (Reykjavík)"
pf_id = "exit3"
rdomain = 53
iface = "wg53"
iface_ip = "10.0.0.2/24"
wg_key = "example_wg_private_key"
wg_peer_pub = "example_wg_peer_public_key"
wg_peer_endpoint_ip = "reykjavik.someothervpn.example"
wg_peer_endpoint_port = 51820
gateway_ip = "10.0.0.1"
table_persist_path = "/var/teleport-hub/tables/exit3.txt"
